[package]
name = "webassembly"
version = "0.1.0"
authors = ["Konstantin Petrov <k.petrov@petrel.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
