name: deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing needed Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
    - uses: actions/checkout@v1
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run: |
        npm install
        npm run build
        cargo build --verbose -p kpetrov --release

    - name: Deploy to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        passphrase: ${{ secrets.REMOTE_PASSPHRASE }}
        source: "./frontend/dist/.*"
        target: ${{ secrets.REMOTE_TARGET }}

    - name: Package
      shell: bash
      run: |
        tar czvf target/kpetrov.tar.gz frontend/dist
        zip -r target/kpetrov.zip frontend/dist
        shasum -a 256 target/kpetrov.tar.gz > target/kpetrov.tar.gz.sha256
        shasum -a 256 target/kpetrov.zip > target/kpetrov.zip.sha256
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/kpetrov.tar.gz
          target/kpetrov.tar.gz.sha256
          target/kpetrov.zip
          target/kpetrov.zip.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
