name: deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing needed Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
    - uses: actions/checkout@v1
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run: |
        npm install
        npm run build
        cargo build --verbose -p blog-wasm --release

    - name: Deploy to DigitalOcean with doctl
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        PORT: ${{ secrets.REMOTE_PORT }}
        KEY: ${{ secrets.REMOTE_SSH_KEY }}
      with:
        source: "./dist"
        target: ${{ secrets.REMOTE_TARGET }}

    - name: Package
      shell: bash
      run: |
        tar czvf target/blog-wasm.tar.gz blog-wasm/dist
        zip -r target/blog-wasm.zip blog-wasm/dist
        shasum -a 256 target/blog-wasm.tar.gz > target/conduit-wasm.tar.gz.sha256
        shasum -a 256 target/blog-wasm.zip > target/conduit-wasm.zip.sha256
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/blog-wasm.tar.gz
          target/blog-wasm.tar.gz.sha256
          target/blog-wasm.zip
          target/blog-wasm.zip.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
