name: deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing needed Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
    - uses: actions/checkout@v1
    - name: Install wasm-pack
      run: cargo install wasm-pack
#    - name: Install Diesil
#      run: cargo install diesel_cli --force \
#        --no-default-features --features "postgres"
    - name: Build
      run: |
        npm install
        npm run build
        cargo build --verbose -p kpetrov --release

    - name: Executing remote ssh commands #TODO Use this for migration
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          while true; do
            if pg_isready -qh localhost; then break; fi
          done
          whoami
#          diesel migration run \
#            --database-url postgres://${{ secrets.PG_USERNAME }}:@${{ secrets.PG_URL }}/database

    - name: Deploy to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        passphrase: ${{ secrets.REMOTE_PASSPHRASE }}
        source: "./dist/*"
        target: ${{ secrets.REMOTE_TARGET }}

    - name: Package
      shell: bash
      run: |
        tar czvf target/kpetrov.tar.gz dist
        zip -r target/kpetrov.zip dist
        shasum -a 256 target/kpetrov.tar.gz > target/kpetrov.tar.gz.sha256
        shasum -a 256 target/kpetrov.zip > target/kpetrov.zip.sha256
    - name: Create Release
      uses: softprops/action-gh-release@v1
      run: echo "Tags are > ${PUSH_TAG_VERSION}"
      with:
        files: |
          target/kpetrov.tar.gz
          target/kpetrov.tar.gz.sha256
          target/kpetrov.zip
          target/kpetrov.zip.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
