name: build

on: 
  push:
    branches: 
      - master
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**cd.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing needed Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
    - uses: actions/checkout@v1
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run: |
        npm install
        npm run build
        cargo build --verbose -p kpetrov
    - name: Run tests
      run: |
        npm run test
        cargo test --verbose -p kpetrov
    - name: cargo fmt & clippy
      run: |
        cargo fmt --all -- --check
        cargo clippy -- --deny=warnings
